// lib/questions.ts — six founder questions in the master-sheet vocabulary.
export const INTAKE_QUESTIONS = [
  {
    id: "stage",
    label: "Where is your venture right now?",
    hint: "Your answer helps us match you with the right funding and the right advisor.",
    options: [
      { value: "1_idea", label: "Research or idea,", sub: "not incorporated yet", icon: "lightbulb" },
      { value: "2_pre_revenue", label: "Building an MVP,", sub: "pre-revenue", icon: "rocket" },
      { value: "3_early_revenue", label: "Launched,", sub: "early revenue", icon: "trendingUp" },
      { value: "4_growth", label: "Growing,", sub: "commercial traction", icon: "building" },
      { value: "5_scale", label: "Scaling up,", sub: "raising a larger round", icon: "users" },
    ],
  },
  {
    id: "sector",
    label: "What sector are you in?",
    hint: "Pick the closest fit. We surface sector-specific programs you might miss.",
    options: [
      { value: "sector_agnostic", label: "General,", sub: "not sector-specific", icon: "target" },
      { value: "software", label: "Software", sub: "", icon: "code" },
      { value: "artificial_intelligence", label: "AI", sub: "", icon: "cpu" },
      { value: "healthcare", label: "Healthcare", sub: "", icon: "heartPulse" },
      { value: "medtech", label: "Medtech", sub: "", icon: "heartPulse" },
      { value: "biotechnology", label: "Biotech", sub: "", icon: "flask" },
      { value: "cleantech", label: "Cleantech", sub: "", icon: "leaf" },
      { value: "advanced_manufacturing", label: "Manufacturing", sub: "", icon: "factory" },
      { value: "agriculture", label: "Agriculture", sub: "", icon: "leaf" },
      { value: "energy", label: "Energy", sub: "", icon: "leaf" },
    ],
  },
  {
    id: "province",
    label: "Where are you based?",
    hint: "We include Canada-wide programs plus ones for your province.",
    options: [
      { value: "qc", label: "Quebec", sub: "", icon: "landmark" },
      { value: "on", label: "Ontario", sub: "", icon: "landmark" },
      { value: "bc", label: "British Columbia", sub: "", icon: "landmark" },
      { value: "ab", label: "Alberta", sub: "", icon: "landmark" },
      { value: "ns", label: "Nova Scotia", sub: "", icon: "landmark" },
      { value: "mb", label: "Manitoba", sub: "", icon: "landmark" },
      { value: "sk", label: "Saskatchewan", sub: "", icon: "landmark" },
      { value: "nb", label: "New Brunswick", sub: "", icon: "landmark" },
      { value: "other", label: "Elsewhere in Canada", sub: "", icon: "target" },
    ],
  },
  {
    id: "applicant_type",
    label: "What best describes you?",
    hint: "Programs are often restricted to certain kinds of applicants.",
    options: [
      { value: "startup_pre_revenue", label: "Startup,", sub: "pre-revenue", icon: "rocket" },
      { value: "sme", label: "Small or medium business", sub: "", icon: "building" },
      { value: "for_profit_company", label: "For-profit company", sub: "", icon: "briefcase" },
      { value: "nonprofit", label: "Nonprofit", sub: "", icon: "users" },
      { value: "academic_institution", label: "Academic,", sub: "research institution", icon: "graduationCap" },
      { value: "individual", label: "Individual,", sub: "researcher or founder", icon: "users" },
      { value: "indigenous_owned", label: "Indigenous-owned", sub: "", icon: "target" },
      { value: "women_owned", label: "Women-owned", sub: "", icon: "target" },
    ],
  },
  {
    id: "activity",
    label: "What do you need funding for?",
    hint: "The main activity you want to finance right now.",
    options: [
      { value: "research_and_development", label: "R&D", sub: "", icon: "flask" },
      { value: "prototype_development", label: "Prototype", sub: "", icon: "rocket" },
      { value: "commercialization", label: "Commercialization", sub: "", icon: "trendingUp" },
      { value: "hiring", label: "Hiring", sub: "", icon: "users" },
      { value: "training", label: "Training", sub: "", icon: "graduationCap" },
      { value: "capital_equipment", label: "Equipment,", sub: "capital", icon: "factory" },
      { value: "export", label: "Export,", sub: "new markets", icon: "trendingUp" },
      { value: "market_research", label: "Market research", sub: "", icon: "target" },
    ],
  },
  {
    id: "funding_preference",
    label: "What kind of funding do you want?",
    hint: "Non-dilutive means you keep your equity.",
    options: [
      { value: "non_dilutive", label: "Non-dilutive,", sub: "grants, credits, contributions", icon: "gift" },
      { value: "equity", label: "Equity,", sub: "venture capital", icon: "trendingUp" },
      { value: "any", label: "Open to anything", sub: "", icon: "target" },
    ],
  },
] as const;
