-- seed_data.sql
-- Run after schema_data.sql. Seeds the 6 placeholder partners.
-- (Funding programs are loaded separately with: npm run seed)

insert into public.partners (id,name,entity_type,partner_kind,industries,personas,segment,location,intro_via_mvc,contact_public,contact,blurb,status,last_reviewed,is_example) values ('ex_health_clinic', '[EXAMPLE] Montreal multi-site medical clinic', 'company', ARRAY['customer','pilot_site']::text[], ARRAY['healthcare']::text[], ARRAY['clinical','operations']::text[], 'mid_market', 'Montreal', true, false, null, 'Replace with a real clinic contact. Useful for founders validating a clinical or patient-facing product with practising clinicians.', 'active', null, true) on conflict (id) do nothing;
insert into public.partners (id,name,entity_type,partner_kind,industries,personas,segment,location,intro_via_mvc,contact_public,contact,blurb,status,last_reviewed,is_example) values ('ex_logistics_ops', '[EXAMPLE] Mid-size Quebec logistics operator', 'company', ARRAY['customer','pilot_site']::text[], ARRAY['logistics','manufacturing']::text[], ARRAY['operations','procurement']::text[], 'mid_market', 'Quebec', true, false, null, 'Replace with a real operations lead. Good for founders selling supply chain, routing, or warehouse tools.', 'active', null, true) on conflict (id) do nothing;
insert into public.partners (id,name,entity_type,partner_kind,industries,personas,segment,location,intro_via_mvc,contact_public,contact,blurb,status,last_reviewed,is_example) values ('ex_fintech_expert', '[EXAMPLE] Former bank operations director', 'person', ARRAY['expert','customer']::text[], ARRAY['finance']::text[], ARRAY['operations','finance_persona','leadership']::text[], 'enterprise', 'Montreal', true, false, null, 'Replace with a real, consented advisor. Useful for founders validating finance or compliance workflows with someone who has bought enterprise software.', 'active', null, true) on conflict (id) do nothing;
insert into public.partners (id,name,entity_type,partner_kind,industries,personas,segment,location,intro_via_mvc,contact_public,contact,blurb,status,last_reviewed,is_example) values ('ex_saas_designpartner', '[EXAMPLE] Growth-stage SaaS company', 'company', ARRAY['design_partner','customer']::text[], ARRAY['software_it']::text[], ARRAY['product','it_engineering']::text[], 'smb', 'Remote', true, false, null, 'Replace with a real design partner. Good for founders selling developer or product tools who want hands-on feedback.', 'active', null, true) on conflict (id) do nothing;
insert into public.partners (id,name,entity_type,partner_kind,industries,personas,segment,location,intro_via_mvc,contact_public,contact,blurb,status,last_reviewed,is_example) values ('ex_retail_buyer', '[EXAMPLE] Independent retail chain', 'company', ARRAY['customer','channel']::text[], ARRAY['retail']::text[], ARRAY['operations','sales_marketing']::text[], 'smb', 'Montreal', true, false, null, 'Replace with a real buyer. Useful for founders validating retail, POS, or consumer products.', 'active', null, true) on conflict (id) do nothing;
insert into public.partners (id,name,entity_type,partner_kind,industries,personas,segment,location,intro_via_mvc,contact_public,contact,blurb,status,last_reviewed,is_example) values ('ex_university_pilot', '[EXAMPLE] University administrative department', 'company', ARRAY['pilot_site','customer']::text[], ARRAY['education','public_sector']::text[], ARRAY['operations','leadership']::text[], 'enterprise', 'Montreal', true, false, null, 'Replace with a real campus contact. Good for founders validating edtech or workflow tools in an institutional setting.', 'active', null, true) on conflict (id) do nothing;
